config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'
  resources :hardwares
  get 'pages/home'
  get 'pages/hardwares'
  get 'pages/contact'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern
	def self.image_generator(width:, height:)
		"http://placehold.it/#{width}x#{height}"
	end
end

app/models/hardware.rb
class Hardware < ApplicationRecord
	# has_rich_text :information_for_us
	# has_rich_text :information_for_user

	include Placeholder
	# validates_presence_of :main_image, :thumb_image
	
	mount_uploader :thumb_image, ImagesUploader
	mount_uploader :main_image, ImagesUploader

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator(width:'600', height:'400')
		self.thumb_image ||= Placeholder.image_generator(width:'320', height:'180')
	end


end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  rolify

  after_create :assign_default_role

  def assign_default_role
  	self.add_role(:user) if self.roles.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hardwares_controller.rb
class HardwaresController < ApplicationController
  before_action :set_hardware, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  # GET /hardwares
  # GET /hardwares.json
  def index
    @hardwares = Hardware.all
    @hardwares_forsale = Hardware.where(:sold => false)
  end

  # GET /hardwares/1
  # GET /hardwares/1.json
  def show
  end

  # GET /hardwares/new
  def new
    @hardware = Hardware.new
  end

  # GET /hardwares/1/edit
  def edit
  end

  # POST /hardwares
  # POST /hardwares.json
  def create
    @hardware = Hardware.new(hardware_params)

    respond_to do |format|
      if @hardware.save
        format.html { redirect_to @hardware, notice: 'Hardware was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /hardwares/1
  # PATCH/PUT /hardwares/1.json
  def update
    respond_to do |format|
      if @hardware.update(hardware_params)
        format.html { redirect_to @hardware, notice: 'Hardware was successfully updated.' }
        format.json { render :show, status: :ok, location: @hardware }
      else
        format.html { render :edit }
        format.json { render json: @hardware.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hardwares/1
  # DELETE /hardwares/1.json
  def destroy
    @hardware.destroy
    respond_to do |format|
      format.html { redirect_to hardwares_url, notice: 'Hardware was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hardware
      @hardware = Hardware.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def hardware_params
      params.require(:hardware).permit(:device_type, :device_model, :sn, :describe, :code_number,
                                       :purchase_price, :sold, :procesor, :ram, :disk, :screen, :dvd,
                                       :video_card, :battery, :operating_system, :warranty, :equipment,
                                       :date_of_purchase, :sale_date, :price, :information_for_us,
                                       :information_for_user, :main_image, :thumb_image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def hardwares
  end

  def contact
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hardwares_helper.rb
module HardwaresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/hardwares/_form.html.haml
= simple_form_for @hardware do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .field
    = f.label "Załaduj piki:"
  %br
    = f.file_field :main_image
  .field
    = f.file_field :thumb_image
  %br
  %br
  .field
    = f.label "Załaduj wiele zdjęć:"
  %br
  .field
  / .row
  /   .col-md-12
  /     = f.fields_for :image do |ff|
  /       .field
  /         = ff.label t :image
  /         %br/
  /         = ff.hidden_field :image_cache
  /         = ff.file_field :image, multiple: true, name: "images[]"
  /         %b
  /         - @hardware.images.each do |image|
  /           = image_tag image.image_url(:hardwares_image)
  /           %h5= link_to "Delete", image_path(image), :method => :delete    
  .field
    = f.label t :device_type
    = f.text_field :device_type
  .field
    = f.label t :device_model
    = f.text_field :device_model
  .field
    = f.label t :sn
    = f.text_field :sn
  .field
    = f.label t :describe
    = f.text_field :describe
  .field
    = f.label t :code_number
    = f.text_field :code_number
  .field
    = f.label t :purchase_price
    = f.text_field :purchase_price
  .field
    = f.label t :procesor
    = f.text_field :procesor
  .field
    = f.label t :ram
    = f.text_field :ram
  .field
    = f.label t :disk
    = f.text_field :disk
  .field
    = f.label t :screen
    = f.text_field :screen
  .field
    = f.label t :dvd
    = f.text_field :dvd
  .field
    = f.label t :video_card
    = f.text_field :video_card
  .field
    = f.label t :battery
    = f.text_field :battery
  .field
    = f.label t :operating_system
    = f.text_field :operating_system
  .field
    = f.label t :warranty
    = f.text_field :warranty
  .field
    = f.label t :equipment
    = f.text_field :equipment
  .field
    = f.label t :date_of_purchase
    = f.date_select :date_of_purchase
  .field
    = f.label t :sold
    = f.check_box :sold
  -if @hardware.sold
    .field
      = f.label t :sale_date
      = f.date_select :sale_date
  .field
    = f.label t :price
    = f.text_field :price
  .field
    = f.label t :information_for_us
    = f.text_area :information_for_us
  .field
    = f.label t :information_for_user
    = f.text_area :information_for_user
  .actions
    = f.submit 'Zapisz'

app/views/hardwares/edit.html.haml
%h1 Edytuj urządzenie

= render 'form'

= link_to 'Show', @hardware
\|
= link_to 'Back', hardwares_path

app/views/hardwares/index.html.haml
.margin-top-25
%h6= "Liczba urządzeń w sprzedaży: #{@hardwares_forsale.count}"
%br
= link_to 'Dodaj nowe urządzenie', new_hardware_path, method: :get, class: 'btn btn-success btn-lg add_hardware_button'

%table.table.table-inverse.table-striped.table-hover.text-center.table-responsive-lg
  %thead.thead-dark
    %tr
      %th
      %th Typ urządzenia
      %th Model urządzenia
      %th Cena zakupu
      %th Sprzedany?
      %th Procesor
      %th Ram
      %th Dysk
      %th Wyświetlacz
      %th Karta graficzna
      %th System operacyjny
      %th Cena sprzedaży
      %th{:colspan => "3"} Co chcesz zrobić?

  %tbody
    - @hardwares.each do |hardware|
      %tr
        %td= image_tag(hardware.thumb_image.url, width: '80px') unless hardware.thumb_image.url.nil?
        %td= hardware.device_type
        %td= hardware.device_model
        %td= hardware.purchase_price
        -if hardware.sold
          %td 
            %span{:style => "color: green;"}
              %i.fas.fa-check
        -else 
          %td
            %span{:style => "color: red;"}
              %i.fas.fa-times  
        %td= hardware.procesor
        %td= hardware.ram
        %td= hardware.disk
        %td= hardware.screen
        %td= hardware.video_card
        %td= hardware.operating_system
        %td= hardware.price
        %td= link_to 'Pokaż', hardware, method: :get, class: 'btn btn-info btn-xm action_color'
        %td= link_to 'Edytuj', edit_hardware_path(hardware), method: :get, class: 'btn btn-warning btn-xm action_color'
        %td= link_to 'Usuń', hardware, method: :delete, data: { confirm: 'Jesteś pewien?' }, class: 'btn btn-danger btn-xm action_color'

%br

= link_to 'Dodaj nowe urządzenie', new_hardware_path, method: :get, class: 'btn btn-success btn-lg add_hardware_button'

app/views/hardwares/new.html.haml
%h1 Dodaj nowe urządzenie

= render 'form'

= link_to 'Back', hardwares_path

app/views/hardwares/show.html.haml
.card
  %p#notice= notice
  .card-body
    .row
      .col-md-3.center
        = image_tag @hardware.main_image.url, width: '320px' unless @hardware.main_image.url.nil?
      .col-md-9.bigtext.font-lucida{:style => "font-size: 3.625rem; text-decoration: underline;"}
        = @hardware.device_type + ' ' + @hardware.device_model
    .row
      .col-md-6
        / %p
        /   .row
        /     .col-md-12
        /       = image_tag @hardware.thumb_image.url, width: '150px'
        / %p
        /   .row
        /     .col-md-3
        /       %b Name:
        /     .col-md-9  
        /       = @hardware.device_type
        / %p
        /   .row
        /     .col-md-3
        /       %b Model:
        /     .col-md-9  
        /       = @hardware.device_model
        %p
          .row
            .col-md-3.p-2
              %b Numer seryjny:
            .col-md-7.shadow.bg-white.rounded.p-2
              = @hardware.sn
        %p
          .row
            .col-md-3.p-2
              %b Opis:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.describe
        %p
          .row
            .col-md-3.p-2
              %b Kod urządzenia:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.code_number
        %p
          .row
            .col-md-3.p-2
              %b Cena zakupu:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.purchase_price
        %p
          .row
            .col-md-3.p-2
              %b Data zakupu:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.date_of_purchase.strftime("%Y-%m-%d")
        %p
          .row
            .col-md-3.p-2
              %b Czy sprzedany:
            .col-md-7.p-2 
              -if @hardware.sold
                %td 
                  %span{:style => "color: green;"}
                    %i.fas.fa-check
              -else 
                %td
                  %span{:style => "color: red;"}
                    %i.fas.fa-times
        -if @hardware.sale_date? && @hardware.sold
          %p
            .row
              .col-md-3.p-2
                %b Data sprzedaży:
              .col-md-7.shadow.bg-white.rounded.p-2 
                = @hardware.sale_date.strftime("%Y-%m-%d")
        %p
          .row
            .col-md-3.p-2
              %b Cena:
            .col-md-3.shadow.bg-white.rounded.p-2 
              = @hardware.price
      .col-md-6
        %p
          .row
            .col-md-3.p-2
              %b Procesor:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.procesor
        %p
          .row
            .col-md-3.p-2.p-2
              %b Ilość pamięci RAM:
            .col-md-7.shadow.bg-white.rounded.p-2
              = @hardware.ram
        %p
          .row
            .col-md-3.p-2
              %b Dysk:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.disk
        %p
          .row
            .col-md-3.p-2
              %b Matryca:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.screen
        %p
          .row
            .col-md-3.p-2
              %b Napęd DVD:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.dvd
        %p
          .row
            .col-md-3.p-2
              %b Karta graficzna:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.video_card
        %p
          .row
            .col-md-3.p-2
              %b Bateria:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.battery
        %p
          .row
            .col-md-3.p-2
              %b System operacyjny:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.operating_system
        %p
          .row
            .col-md-3.p-2
              %b Gwarancja:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.warranty
        %p
          .row
            .col-md-3.p-2
              %b Wyposażenie:
            .col-md-7.shadow.bg-white.rounded.p-2 
              = @hardware.equipment
  .card-footer
    %p
      .row
        .col-md-3.p-2
          %b Informacja tylko dla sprzedającego:
        .col-md-6.shadow.bg-white.rounded.p-2 
          = @hardware.information_for_us
    %p
      .row
        .col-md-3.p-2
          %b Informacje dla użytkownika:
        .col-md-6.shadow.bg-white.rounded.p-2 
          = @hardware.information_for_user

= link_to 'Edytuj', edit_hardware_path(@hardware)
\|
= link_to 'Powrót do listy urządzeń', hardwares_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "#"} PBKOMP
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
      %li.nav-item.active
        .nav-link
          = link_to 'Start', pages_home_path
          %span.sr-only (current)
      %li.nav-item
        .nav-link
          = link_to 'Urządzenia', hardwares_path
      %li.nav-item.dropdown
        %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Oferta
        .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
          %a.dropdown-item{:href => "#"} Internet szerokopasmowy
          %a.dropdown-item{:href => "#"} Internet światłowodowy
          .dropdown-divider
          %a.dropdown-item{:href => "#"} Systemy monitoringu
          %a.dropdown-item{:href => "#"} Systemy alarmowe
          %a.dropdown-item{:href => "#"} Domofony / Wideodomofony
          .dropdown-divider
          %a.dropdown-item{:href => "#"} Serwis sprzętu komputerowego
          .dropdown-divider
          %a.dropdown-item{:href => "#"} Cennik usług
      %li.nav-item.active
        .nav-link
          = link_to 'Kontakt', pages_contact_path
    %form.form-inline.my-2.my-lg-0
      %input.form-control.mr-sm-2{"aria-label" => "Search", :placeholder => "Szukaj", :type => "search"}/
      %button.btn.btn-outline-success.my-2.my-sm-0{:type => "submit"} Szukaj
      - if current_user
        = current_user.email
        = link_to 'Account settings', edit_user_registration_path
        = link_to 'Sign out', destroy_user_session_path, method: :delete
      - else
        = link_to 'Sign Up', new_user_registration_path
        = link_to 'Log In', new_user_session_path

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role => "alert"}
      %button.close{:type => 'button', "data-dissmis" => "alert"}
        %span{'aria-hidden' => 'true'}= raw '&times;'
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/application.html.haml
!!!
%html
	%head
		%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
		%title Pbk
		= csrf_meta_tags
		= csp_meta_tag
		= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
		= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
	%body
		= render 'layouts/header'
		= render 'layouts/messages'
		= yield

app/views/pages/contact.html.haml
.jumbotron.jumbotron-fluid
	.container
		%h3 Dane kontaktowe
		%p Firma PBKOMP Paweł Brzózka
		%p Majdan Sieniawski 366
		%p 37-534 Adamówka
		%p tel. 177877137, 504518290
		%p email: pbkomp@biznespoczta.pl
		%p nr konta bankowego: 64 1140 2004 0000 3202 3572 9289
		%p Regon: 651554527

app/views/pages/hardwares.html.haml
%h1 Pages#hardwares

app/views/pages/home.html.haml
%h1 Strona główna
%p Aktualizacja wkrótce ...